package com.lazyapps.wifianalyzer.ui.importcsv

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.lazyapps.wifianalyzer.R
import com.lazyapps.wifianalyzer.importcsv.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun ImportScreen(onBack: () -> Unit, vm: ImportViewModel = viewModel()) {
    val state by vm.state.collectAsStateWithLifecycle()
    val picker = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri -> uri?.let(vm::select) }
    val errorSaver = rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("text/csv")) { uri -> uri?.let(vm::writeErrorCsv) }
    Scaffold(topBar = { TopAppBar(title = { Text(stringResource(R.string.csv_import_title)) }, navigationIcon = { TextButton(onClick = if (state.step == ImportStep.SELECT) onBack else vm::back) { Text(stringResource(R.string.back)) } }) }) { padding ->
        LazyColumn(Modifier.fillMaxSize().padding(padding).testTag("csv_import_screen"), contentPadding = PaddingValues(20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            item { Text(stepLabel(state.step), style = MaterialTheme.typography.headlineSmall); state.error?.let { Text(it, color = MaterialTheme.colorScheme.error) } }
            when (state.step) {
                ImportStep.SELECT -> item { Button(onClick = { picker.launch(arrayOf("text/csv", "text/plain", "application/vnd.ms-excel", "*/*")) }, modifier = Modifier.testTag("select_csv")) { Text(stringResource(R.string.csv_select_file)) } }
                ImportStep.ENCODING -> item { Text(state.fileName); Text(stringResource(R.string.csv_detected_encoding, state.encoding.label, if (state.hasBom) "BOM" else stringResource(R.string.none))); ChoiceRow("UTF-8", state.encoding == CsvEncoding.UTF8) { vm.setEncoding(CsvEncoding.UTF8) }; ChoiceRow("Windows-31J", state.encoding == CsvEncoding.WINDOWS_31J) { vm.setEncoding(CsvEncoding.WINDOWS_31J) }; NextButton(vm::next) }
                ImportStep.MAPPING -> { items(state.headers.indices.toList()) { index -> MappingRow(state.headers[index], state.samples.firstOrNull()?.getOrNull(index).orEmpty(), state.mapping[index]) { vm.setMapping(index, it) } }; item { NextButton(vm::next) } }
                ImportStep.SETTINGS -> item { Settings(state.settings, vm::setSettings); NextButton(vm::next) }
                ImportStep.PREVIEW -> { val p = state.preview!!; item { Text(stringResource(R.string.csv_preview_counts, p.total, p.additions, p.updates, p.skips, p.errors, p.conflicts)); Text(stringResource(R.string.csv_preview_created, p.workspaceNames.size, p.groupNames.size, p.warnings)); FilterChip(state.showErrorsOnly, vm::toggleErrors, { Text(stringResource(R.string.csv_errors_only)) }) }; items(p.rows.filter { !state.showErrorsOnly || it.status in setOf(ImportRowStatus.ERROR, ImportRowStatus.CONFLICT) }.take(50)) { Text(stringResource(R.string.csv_row_summary, it.source.sourceRow, rowStatusLabel(it.status), it.source.deviceName, importMessages(it.messages))) }; item { NextButton(vm::next) } }
                ImportStep.CONFIRM -> item { val p = state.preview!!; Text(stringResource(if (state.settings.errorMode == ErrorMode.VALID_ROWS_ONLY) R.string.csv_confirm_valid_only else R.string.csv_confirm_rollback, p.additions + p.updates)); Button(onClick = vm::execute, enabled = !state.busy, modifier = Modifier.testTag("execute_import")) { Text(stringResource(R.string.csv_execute)) } }
                ImportStep.IMPORTING -> item { LinearProgressIndicator(Modifier.fillMaxWidth()); Text(stringResource(R.string.csv_importing)); OutlinedButton(onClick = vm::cancel) { Text(stringResource(R.string.cancel)) } }
                ImportStep.RESULT -> item { val r = state.result!!; Text(stringResource(R.string.csv_result_counts, r.added, r.updated, r.skipped, r.errors)); Text(stringResource(R.string.csv_result_created, r.workspacesCreated, r.groupsCreated, r.bssidsRegistered)); Text(stringResource(R.string.csv_elapsed, r.elapsedMillis)); if (r.errors > 0) OutlinedButton(onClick = { errorSaver.launch("WiFiAnalyzer_ImportErrors.csv") }, modifier = Modifier.testTag("save_import_errors")) { Text(stringResource(R.string.csv_save_errors)) }; Button(onClick = onBack) { Text(stringResource(R.string.done)) } }
            }
        }
    }
}

@Composable private fun NextButton(onClick: () -> Unit) = Button(onClick, Modifier.testTag("import_next")) { Text(stringResource(R.string.next)) }
@Composable private fun ChoiceRow(label: String, selected: Boolean, onClick: () -> Unit) = Row { RadioButton(selected, onClick); Text(label, Modifier.padding(top = 12.dp)) }
@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun MappingRow(header: String, sample: String, selected: ImportField, onSelect: (ImportField) -> Unit) { var open by remember { mutableStateOf(false) }; Column { Text(stringResource(R.string.csv_mapping_sample, header, sample.take(50))); ExposedDropdownMenuBox(open, { open = it }) { OutlinedTextField(fieldLabel(selected), {}, readOnly = true, modifier = Modifier.menuAnchor().fillMaxWidth()); ExposedDropdownMenu(open, { open = false }) { ImportField.entries.forEach { field -> DropdownMenuItem({ Text(fieldLabel(field)) }, { onSelect(field); open = false }) } } } } }
@Composable private fun Settings(s: ImportSettings, set: (ImportSettings) -> Unit) { Text(stringResource(R.string.csv_import_mode)); ChoiceRow(stringResource(R.string.csv_add_only), s.mode == ImportMode.ADD_ONLY) { set(s.copy(mode = ImportMode.ADD_ONLY)) }; ChoiceRow(stringResource(R.string.csv_add_update), s.mode == ImportMode.ADD_AND_UPDATE) { set(s.copy(mode = ImportMode.ADD_AND_UPDATE)) }; Text(stringResource(R.string.csv_match_key)); MatchKey.entries.forEach { ChoiceRow(matchKeyLabel(it), s.matchKey == it) { set(s.copy(matchKey = it)) } }; Text(stringResource(R.string.workspace)); ChoiceRow(stringResource(R.string.csv_use_workspace_column), s.workspaceMode == WorkspaceMode.CSV) { set(s.copy(workspaceMode = WorkspaceMode.CSV)) }; ChoiceRow(stringResource(R.string.csv_use_current_workspace), s.workspaceMode == WorkspaceMode.CURRENT) { set(s.copy(workspaceMode = WorkspaceMode.CURRENT)) }; Text(stringResource(R.string.csv_error_rows)); ChoiceRow(stringResource(R.string.csv_abort_all), s.errorMode == ErrorMode.ABORT_ALL) { set(s.copy(errorMode = ErrorMode.ABORT_ALL)) }; ChoiceRow(stringResource(R.string.csv_valid_only), s.errorMode == ErrorMode.VALID_ROWS_ONLY) { set(s.copy(errorMode = ErrorMode.VALID_ROWS_ONLY)) }; Text(stringResource(R.string.csv_blank_cells)); ChoiceRow(stringResource(R.string.csv_keep_existing), s.blankMode == BlankMode.KEEP) { set(s.copy(blankMode = BlankMode.KEEP)) }; ChoiceRow(stringResource(R.string.csv_clear_existing), s.blankMode == BlankMode.CLEAR) { set(s.copy(blankMode = BlankMode.CLEAR)) }; Text(stringResource(R.string.csv_bssid_update)); ChoiceRow(stringResource(R.string.csv_append_bssid), s.bssidMode == BssidUpdateMode.APPEND) { set(s.copy(bssidMode = BssidUpdateMode.APPEND)) }; ChoiceRow(stringResource(R.string.csv_replace_bssid), s.bssidMode == BssidUpdateMode.REPLACE) { set(s.copy(bssidMode = BssidUpdateMode.REPLACE)) } }

@Composable private fun fieldLabel(field: ImportField) = stringResource(when (field) { ImportField.UNUSED -> R.string.csv_field_unused; ImportField.WORKSPACE -> R.string.workspace; ImportField.GROUP -> R.string.group; ImportField.DEVICE_NAME -> R.string.device_name_required; ImportField.MANUFACTURER -> R.string.manufacturer; ImportField.MODEL -> R.string.model; ImportField.SERIAL -> R.string.serial_number; ImportField.SSID -> R.string.ssid; ImportField.PRIMARY_BSSID -> R.string.csv_field_primary_bssid; ImportField.ALL_BSSIDS -> R.string.csv_field_all_bssids; ImportField.LOCATION -> R.string.installation_location; ImportField.NOTES -> R.string.notes; ImportField.CREATED_AT -> R.string.created_at; ImportField.UPDATED_AT -> R.string.updated_at })
@Composable private fun matchKeyLabel(key: MatchKey) = stringResource(when (key) { MatchKey.AUTO -> R.string.csv_match_auto; MatchKey.SERIAL -> R.string.serial_number; MatchKey.PRIMARY_BSSID -> R.string.csv_field_primary_bssid; MatchKey.ANY_BSSID -> R.string.csv_match_any_bssid; MatchKey.NAME_AND_WORKSPACE -> R.string.csv_match_name_workspace })
@Composable private fun rowStatusLabel(status: ImportRowStatus) = stringResource(when (status) { ImportRowStatus.NEW -> R.string.csv_status_new; ImportRowStatus.UPDATE -> R.string.csv_status_update; ImportRowStatus.SKIP -> R.string.csv_status_skip; ImportRowStatus.ERROR -> R.string.csv_status_error; ImportRowStatus.CONFLICT -> R.string.csv_status_conflict })
@Composable private fun importMessages(codes: List<String>): String { val messages = mutableListOf<String>(); for (code in codes) messages += importMessage(code); return messages.joinToString() }
@Composable private fun importMessage(code: String): String = when { code.startsWith("DUPLICATE_FIELD:") -> stringResource(R.string.csv_duplicate_field, fieldLabel(runCatching { ImportField.valueOf(code.substringAfter(':')) }.getOrDefault(ImportField.UNUSED))); else -> stringResource(when (code) { "MISSING_DEVICE_NAME_COLUMN" -> R.string.csv_missing_device_column; "DEVICE_NAME_REQUIRED" -> R.string.csv_device_name_required; "DEVICE_NAME_TOO_LONG" -> R.string.csv_device_name_too_long; "TOO_MANY_BSSIDS" -> R.string.csv_too_many_bssids; "INVALID_BSSID" -> R.string.csv_invalid_bssid; "CREATED_AT_CORRECTED" -> R.string.csv_created_at_corrected; "DUPLICATE_CSV_DEVICE" -> R.string.csv_duplicate_device; "MULTIPLE_DEVICE_MATCHES" -> R.string.csv_multiple_matches; "BSSID_IN_OTHER_DEVICE" -> R.string.csv_bssid_conflict; "EXISTING_DEVICE_MATCH" -> R.string.csv_existing_match; else -> R.string.error_invalid_csv }) }
@Composable private fun stepLabel(step: ImportStep) = stringResource(when(step) { ImportStep.SELECT -> R.string.csv_step_select; ImportStep.ENCODING -> R.string.csv_step_encoding; ImportStep.MAPPING -> R.string.csv_step_mapping; ImportStep.SETTINGS -> R.string.csv_step_settings; ImportStep.PREVIEW -> R.string.csv_step_preview; ImportStep.CONFIRM -> R.string.csv_step_confirm; ImportStep.IMPORTING -> R.string.csv_step_importing; ImportStep.RESULT -> R.string.csv_step_result })
